# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         psh
version:      1.8.1.001
version_from: lib/Psh.pm
installdirs:  site
requires:
    Cwd:                           0
    File::Spec:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
